name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install stable rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.6.3"
          rebar3-version: "3"
          # elixir-version: "1.15.4"
      - run: ./build_ortex.sh
      - run: gleam deps download
      - run: gleam test
      - run: gleam format --check src test
